# @package _global_

logs: ['Log1', 'Log2', 'Log3', 'Log4', 'Log5', 'Log6']
camera: ['camera']

##-----------------------------------------------------#
# Training parameters
NUM_EPOCHS: 25
BATCH_SIZE: 64
NUM_WORKERS: 8
LEARNING_RATE: 0.0001
WEIGHT_DECAY: 1e-6
DROP_OUT: 0.20
TEST_SIZE: 0.15
VALID_SIZE: 0.15


### data loading paramters
gray_scale: False
crop_sky: True
loading_mode: 'single'                     # single, multiple or multiple_frameskip
modalities: ['camera', 'semantic_label']   # 'camera' must exist

obs_size: 1 #4
n_actions: 9
frame_skip: 4

train_logs: ['Log1']
test_logs: ['Log2']
image_size: [1, 256, 256]
alpha: 0.75
beta: 0.1
