# @package _global_

# specify here default training configuration
defaults:
    - model: vae.yaml
    - seeds: default_seeds.yaml

# output paths for hydra logs
log_dir: logs/${now:%Y-%m-%d}
# data_dir: data/
data_dir: ../data/data6/
