##-----------------------------------------------------#
# Training parameters
NUM_EPOCHS: 200
BATCH_SIZE: 64
LEARNING_RATE: 0.0001
DROP_OUT: 0.20
TEST_SIZE: 0.15
VALID_SIZE: 0.15

obs_size: 4
n_actions: 3
frame_skip: 4

image_size: [1, 224, 224]
alpha: 0.75
beta: 0.1
number_workers: 8

data_split:
  training:
    town: ['Town05_Opt']
    season: ['ClearNoon', 'HardRainNoon', 'HardRainSunset']
    behavior: ['normal', 'catious']
  validation:
    town: ['Town05_Opt']
    season: ['ClearSunset']
    behavior: ['normal']
  testing:
    town: []
    season: []
    behavior: []

##-----------------------------------------------------#
# Path
training_dataset: '/home/hemanth/Desktop/data/ClearNoon_Town05_Opt.tar'
validation_dataset: '/home/hemanth/Desktop/data/ClearNoon_Town05_Opt.tar'
logs_path: 'logs/'
raw_data_path: 'data/raw'
train_data_path: 'data/raw/train'
val_data_path: 'data/raw/validation'
test_data_path: 'data/raw/test'

pytorch_seed: 1337
