##-----------------------------------------------------#
# Training parameters
NUM_EPOCHS: 100
BATCH_SIZE: 64
LEARNING_RATE: 0.0001
DROP_OUT: 0.20
TEST_SIZE: 0.15
VALID_SIZE: 0.15

##-----------------------------------------------------#
# Data Parameters
obs_size: 1
n_actions: 3
frame_skip: 4
branch_weight: 1
speed_weight: 1
number_workers: 4

##-----------------------------------------------------#
# Other parameters
image_size: [1, 224, 224]
image_resize: [1, 128, 128]
alpha: 0.75
beta: 0.1

##-----------------------------------------------------#
# Data splitting scheme
data_split:
  training:
    town: ['Town01']
    season:
      [
        ClearNoon',
        'SoftRainNoon',
        'HardRainNoon',
        'SoftRainSunset',
        'HardRainSunset',
      ]
    behavior: ['normal', 'catious']
  validation:
    town: ['Town01']
    season: ['ClearSunset']
    behavior: ['normal']
  testing:
    town: []
    season: []
    behavior: []

##-----------------------------------------------------#
# Path(s)
raw_data_path: '/home/hemanth/Desktop/carla_data/Town01/'
# raw_data_path: '../carla_data/Town01/'
logs_path: 'logs/'
train_data_path: 'data/raw/train'
val_data_path: 'data/raw/validation'
test_data_path: 'data/raw/test'

check_point_path: null

##-----------------------------------------------------#
# Benchmark config
benchmark_config:
  benchmark: 'corl2017'
  city_name: 'Town01'
  log_name: local_test
  continue_experiment: False
  host: null
  port: null

##-----------------------------------------------------#
# Carla server parameters
carla_server:
  host: 'localhost'
  retries_on_error: 25
  resolution_x: 600
  resolution_y: 600
  quality_level: 'Low'
  enable_map_assets: True
  enable_rendering: True
  show_display: True
  carla_path: '/home/hemanth/Carla/CARLA_0.9.11'

pytorch_seed: 1337
